name = "nekonymous"
main = "src/index.ts"
compatibility_date = "2024-08-19"

workers_dev = true

kv_namespaces = [
  { binding = "NekonymousKV", id = "de26a1b398614383a2b9702fafaa8824" },
]

[placement]
mode = "smart"

[vars]


[durable_objects]
bindings = [{ name = "INBOX_DO", class_name = "InboxDurableObject" }]

[[migrations]]
tag = "v1"                           # Increment this tag each time you make changes to Durable Objects
new_classes = ["InboxDurableObject"]
