name = "nekonymous"
main = "src/index.ts"
compatibility_date = "2024-08-19"

workers_dev = true

kv_namespaces = [
    { binding = "NekonymousKV", id = "de26a1b398614383a2b9702fafaa8824" },
]

r2_buckets = [
  { binding = "nekonymousr2", bucket_name = "nekonymousr2"}
]
[placement]
mode = "smart"

[vars]
